### ISSUE TITLE
feature request: Enable GET API, or add a compele list in the repo

### ISSUE THREAD

**Issue by gaocegege** [domeccleston/sharegpt#70] opened 2023-03-31 04:15 UTC
https://github.com/lm-sys/FastChat#data

FastChat uses ShareGPT API to get conversation data. We disabled the GET API in https://github.com/domeccleston/sharegpt/commit/b22d58dbe2b523d92675abf915aeeb8f2cc1a5be

Could we provide a complete JSON list or enable the get API again?

I'd appreciate it.

**Comment by nwhitehead** [comment] 2023-03-31 15:25
It's probably a good idea to update the README with the status of the GET API whichever way this is resolved.

**Comment by gaocegege** [comment] 2023-04-01 01:31
> It's probably a good idea to update the README with the status of the GET API whichever way this is resolved.

Yeah, I think so.

**Comment by domeccleston** [comment] 2023-04-03 19:11
This is documented. Closing as duplicate of https://github.com/domeccleston/sharegpt/issues/71

**Closed by domeccleston** 2023-04-03 19:11 UTC
